# Generated by Django 2.2 on 2021-11-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('spot_num', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'spot',
            },
        ),
        migrations.CreateModel(
            name='CameraInfo',
            fields=[
                ('camera_info_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=500, null=True)),
                ('spots', models.ManyToManyField(null=True, related_name='camera_infos', to='coroutine.Spot')),
            ],
            options={
                'db_table': 'camera_info',
            },
        ),
    ]
