# Generated by Django 2.2 on 2021-11-03 07:08

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('coroutine', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate, new table
                # name from AuthorBook._meta.db_table.
                migrations.RunSQL(
                    sql='ALTER TABLE "camera_info_spots" RENAME COLUMN "camerainfo_id" TO "camera_info_id";',
                    #reverse_sql='ALTER TABLE camera_info_spots  RENAME TO camera_info_spots_bak',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CamerasSpots',
                    fields=[
                        (
                            'id',
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        (
                            'camera_info',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='coroutine.CameraInfo',
                            ),
                        ),
                        (
                            'spot',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='coroutine.Spot',
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'camera_info_spots',
                    }
                ),
                migrations.AlterField(
                    model_name='camerainfo',
                    name='spots',
                    field=models.ManyToManyField(null=True, related_name='camera_infos', through='coroutine.CamerasSpots',
                                               to='coroutine.Spot')
                ),
            ],
        ),
        migrations.AddField(
            model_name='camerasspots',
            name='sort',
            field=models.IntegerField(default=0, null=True)
        ),
        migrations.AddField(
            model_name='camerasspots',
            name='remark',
            field=models.CharField(max_length=500, null=True)
        ),

    ]
