# Generated by Django 2.2 on 2021-07-07 02:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_image', '0002_auto_20210421_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags_view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tags_view',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
