# Generated by Django 2.2 on 2021-09-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_image', '0003_auto_20210707_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(related_name='teachers', to='push_image.Student')),
            ],
        ),
    ]
